import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cn } from "~/lib/utils";
import { ThemeToggle } from "~/components/ui/theme-toggle";
import { ThemeProvider } from "~/components/theme-provider";
import { JotaiProvider } from "~/components/jotai-provider";
import { FloatingControls } from "~/components/floating-controls";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}>
        <JotaiProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="absolute right-0 top-0 z-10 flex w-fit justify-end  p-4">
              <ThemeToggle />
            </header>

            <FloatingControls />

            <main>{children}</main>
          </ThemeProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
