import type { DropzoneState, Extension, MimeType } from "./types";

export const FILES_TO_IGNORE = [
  // Thumbnail cache files for macOS and Windows
  ".DS_Store", // macOs
  "Thumbs.db", // Windows
];

// https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
export const extensions = [
  "aac",
  "abw",
  "arc",
  "avif",
  "avi",
  "azw",
  "bin",
  "bmp",
  "bz",
  "bz2",
  "cda",
  "csh",
  "css",
  "csv",
  "doc",
  "docx",
  "eot",
  "epub",
  "gz",
  "gif",
  "heic",
  "heif",
  "htm",
  "html",
  "ico",
  "ics",
  "jar",
  "jpeg",
  "jpg",
  "js",
  "json",
  "jsonld",
  "mid",
  "midi",
  "mjs",
  "mp3",
  "mp4",
  "mpeg",
  "mpkg",
  "odp",
  "ods",
  "odt",
  "oga",
  "ogv",
  "ogx",
  "opus",
  "otf",
  "png",
  "pdf",
  "php",
  "ppt",
  "pptx",
  "rar",
  "rtf",
  "sh",
  "svg",
  "swf",
  "tar",
  "tif",
  "tiff",
  "ts",
  "ttf",
  "txt",
  "vsd",
  "wav",
  "weba",
  "webm",
  "webp",
  "woff",
  "woff2",
  "xhtml",
  "xls",
  "xlsx",
  "xml",
  "xul",
  "zip",
  "7z",
  "mkv",
  "mov",
  "msg",
] as const;

export const extensionsWithDot = [
  ".aac",
  ".abw",
  ".arc",
  ".avif",
  ".avi",
  ".azw",
  ".bin",
  ".bmp",
  ".bz",
  ".bz2",
  ".cda",
  ".csh",
  ".css",
  ".csv",
  ".doc",
  ".docx",
  ".eot",
  ".epub",
  ".gz",
  ".gif",
  ".heic",
  ".heif",
  ".htm",
  ".html",
  ".ico",
  ".ics",
  ".jar",
  ".jpeg",
  ".jpg",
  ".js",
  ".json",
  ".jsonld",
  ".mid",
  ".midi",
  ".mjs",
  ".mp3",
  ".mp4",
  ".mpeg",
  ".mpkg",
  ".odp",
  ".ods",
  ".odt",
  ".oga",
  ".ogv",
  ".ogx",
  ".opus",
  ".otf",
  ".png",
  ".pdf",
  ".php",
  ".ppt",
  ".pptx",
  ".rar",
  ".rtf",
  ".sh",
  ".svg",
  ".swf",
  ".tar",
  ".tif",
  ".tiff",
  ".ts",
  ".ttf",
  ".txt",
  ".vsd",
  ".wav",
  ".weba",
  ".webm",
  ".webp",
  ".woff",
  ".woff2",
  ".xhtml",
  ".xls",
  ".xlsx",
  ".xml",
  ".xul",
  ".zip",
  ".7z",
  ".mkv",
  ".mov",
  ".msg",
] as const;

export const mimeTypes = [
  "audio/aac",
  "application/x-abiword",
  "application/x-freearc",
  "image/avif",
  "video/x-msvideo",
  "application/vnd.amazon.ebook",
  "application/octet-stream",
  "image/bmp",
  "application/x-bzip",
  "application/x-bzip2",
  "application/x-cdf",
  "application/x-csh",
  "text/css",
  "text/csv",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-fontobject",
  "application/epub+zip",
  "application/gzip",
  "image/gif",
  "image/heic",
  "image/heif",
  "text/html",
  "text/html",
  "image/vnd.microsoft.icon",
  "text/calendar",
  "application/java-archive",
  "image/jpeg",
  "image/jpeg",
  "text/javascript",
  "application/json",
  "application/ld+json",
  "audio/midi",
  "audio/midi",
  "text/javascript",
  "audio/mpeg",
  "video/mp4",
  "video/mpeg",
  "application/vnd.apple.installer+xml",
  "application/vnd.oasis.opendocument.presentation",
  "application/vnd.oasis.opendocument.spreadsheet",
  "application/vnd.oasis.opendocument.text",
  "audio/ogg",
  "video/ogg",
  "application/ogg",
  "audio/opus",
  "font/otf",
  "image/png",
  "application/pdf",
  "application/x-httpd-php",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.rar",
  "application/rtf",
  "application/x-sh",
  "image/svg+xml",
  "application/x-shockwave-flash",
  "application/x-tar",
  "image/tiff",
  "image/tiff",
  "video/mp2t",
  "font/ttf",
  "text/plain",
  "application/vnd.visio",
  "audio/wav",
  "audio/webm",
  "video/webm",
  "image/webp",
  "font/woff",
  "font/woff2",
  "application/xhtml+xml",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/xml",
  "application/vnd.mozilla.xul+xml",
  "application/zip",
  "application/x-7z-compressed",
  "video/x-matroska",
  "video/quicktime",
  "application/vnd.ms-outlook",
] as const;

export const COMMON_MIME_TYPES = new Map<Extension, MimeType>([
  ["aac", "audio/aac"],
  ["abw", "application/x-abiword"],
  ["arc", "application/x-freearc"],
  ["avif", "image/avif"],
  ["avi", "video/x-msvideo"],
  ["azw", "application/vnd.amazon.ebook"],
  ["bin", "application/octet-stream"],
  ["bmp", "image/bmp"],
  ["bz", "application/x-bzip"],
  ["bz2", "application/x-bzip2"],
  ["cda", "application/x-cdf"],
  ["csh", "application/x-csh"],
  ["css", "text/css"],
  ["csv", "text/csv"],
  ["doc", "application/msword"],
  ["docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
  ["eot", "application/vnd.ms-fontobject"],
  ["epub", "application/epub+zip"],
  ["gz", "application/gzip"],
  ["gif", "image/gif"],
  ["heic", "image/heic"],
  ["heif", "image/heif"],
  ["htm", "text/html"],
  ["html", "text/html"],
  ["ico", "image/vnd.microsoft.icon"],
  ["ics", "text/calendar"],
  ["jar", "application/java-archive"],
  ["jpeg", "image/jpeg"],
  ["jpg", "image/jpeg"],
  ["js", "text/javascript"],
  ["json", "application/json"],
  ["jsonld", "application/ld+json"],
  ["mid", "audio/midi"],
  ["midi", "audio/midi"],
  ["mjs", "text/javascript"],
  ["mp3", "audio/mpeg"],
  ["mp4", "video/mp4"],
  ["mpeg", "video/mpeg"],
  ["mpkg", "application/vnd.apple.installer+xml"],
  ["odp", "application/vnd.oasis.opendocument.presentation"],
  ["ods", "application/vnd.oasis.opendocument.spreadsheet"],
  ["odt", "application/vnd.oasis.opendocument.text"],
  ["oga", "audio/ogg"],
  ["ogv", "video/ogg"],
  ["ogx", "application/ogg"],
  ["opus", "audio/opus"],
  ["otf", "font/otf"],
  ["png", "image/png"],
  ["pdf", "application/pdf"],
  ["php", "application/x-httpd-php"],
  ["ppt", "application/vnd.ms-powerpoint"],
  ["pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"],
  ["rar", "application/vnd.rar"],
  ["rtf", "application/rtf"],
  ["sh", "application/x-sh"],
  ["svg", "image/svg+xml"],
  ["swf", "application/x-shockwave-flash"],
  ["tar", "application/x-tar"],
  ["tif", "image/tiff"],
  ["tiff", "image/tiff"],
  ["ts", "video/mp2t"],
  ["ttf", "font/ttf"],
  ["txt", "text/plain"],
  ["vsd", "application/vnd.visio"],
  ["wav", "audio/wav"],
  ["weba", "audio/webm"],
  ["webm", "video/webm"],
  ["webp", "image/webp"],
  ["woff", "font/woff"],
  ["woff2", "font/woff2"],
  ["xhtml", "application/xhtml+xml"],
  ["xls", "application/vnd.ms-excel"],
  ["xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
  ["xml", "application/xml"],
  ["xul", "application/vnd.mozilla.xul+xml"],
  ["zip", "application/zip"],
  ["7z", "application/x-7z-compressed"],

  // Others
  ["mkv", "video/x-matroska"],
  ["mov", "video/quicktime"],
  ["msg", "application/vnd.ms-outlook"],
]);

export const initialDropzoneState: DropzoneState = {
  isFocused: false,
  isFileDialogActive: false,
  isDragActive: false,
  isDragAccept: false,
  isDragReject: false,
  acceptedFiles: [],
  rejectedFiles: [],
};
